### ISSUE TITLE
Where is FS_Demo_Data.zip?

### ISSUE THREAD

**Issue by dennyeapen** [MicrosoftLearning/MB-240-Dynamics365forFieldService#2]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by ZekeStarr** [comment]
.

**Comment by julians1966** [comment]
The demo data can be found at https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/tree/master/Instructions/Labs
