### ISSUE TITLE
Not access to the open enviroment 

### ISSUE THREAD

**Issue by palomaseto** [MicrosoftLearning/MB-240-Dynamics365forFieldService#26]
# Module: 00
#### Step: 1 &2

Description of issue
I can access to  https://admin.powerplatform.microsoft.com/ and log in with your Dynamics 365 tenant credentials. My Company tenant
Repro steps:

1.access to the company tenants
1. clik to envoroment are empty
1.[Lab 0: Validate lab environment (5 minutes)](https://microsoftlearning.github.io/MB-240-Dynamics365forFieldService/Instructions/Labs/LAB%5BMB-240%5D_Lab00_Dynamics_365_Labs.html)

**Comment by davidop** [comment]
I am logged against my corporate tenant. I understand that this link should take us to a Dynamics 365 tenant that will already have the environments created, right?

**Comment by julians1966** [comment]
These steps are to be used with a tenant provided by a Microsoft Authorized Lab Hoster (ALH). They are not meant to be used with your own company's corporate tenant.

**Comment by julians1966** [comment]
If you are not using an ALH tenant then you will need to create your own Microsoft 365/Azure AD tenant and add a Dynamics 365 trial - see my instructions https://tinyurl.com/trydyn on the steps to do this

**Comment by trfor** [comment]
Closing issue as this does not follow the process of using a Microsoft Authorized ALH.
