### ISSUE TITLE
[Application] Not An Option

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/MB-240-Dynamics365forFieldService#4]
# Module: 00
#### Step: 03

Description of issue

The instruction [Application.] Appears to potentially be a placeholder.   Logging into the environment, as directed. The following options are present:

![image](https://user-images.githubusercontent.com/41710326/96290053-a0691e80-0fab-11eb-9689-ba80ec11ed1c.png)

Which option should be selected to proceed please?

Thank you

**Comment by mreherefortea** [comment]
Hello Team:

Did you get a chance to look at this please?

**Comment by mreherefortea** [comment]
Hello Team: has anyone had a chance to review this please?

**Comment by julians1966** [comment]
Looks like Field Service has not been installed on your tenant. 
The MB-230 labs have been completely refreshed so this issue no longer applies.
