### ISSUE TITLE
Lab Issues 

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/MB-240-Dynamics365forFieldService#5]
Module 0: Course introduction
Practice Lab - Validate lab environment

Issue: Task 2: Access the Dynamics 365 Application  does not work as authored or with the tenant.  In order to get this working, go to Environments and click + New

![image](https://user-images.githubusercontent.com/41710326/104529809-2e1ad100-55d0-11eb-8c28-262ac5854744.png)
 

Enter a unique Name, Type should be Sandbox, Ensure Yes is selected for Create a database for this environment as shown:
 
![image](https://user-images.githubusercontent.com/41710326/104529820-3541df00-55d0-11eb-88f8-45fb83911020.png)

Click Next
Select Yes for Enable Dynamics 365 Apps and then in the Automatically deploy these apps, select Field Service 
 
![image](https://user-images.githubusercontent.com/41710326/104529842-425ece00-55d0-11eb-99ce-ec2dd3093efc.png)

Then click Save. Wait for your environment to finish provisioning and then select it. 

Practice Lab 1 - Configure Dynamics 365 Field Service
Task 2 - Add Printer Products to a Price List
Step 3:  

![image](https://user-images.githubusercontent.com/41710326/104529875-5276ad80-55d0-11eb-9a32-d6d761a019d7.png)

Issue: There is no Default price list listed to activate. 

Work-around:   
1.	Click New. 
2.	In the Name field, enter Default.  
3.	Click Save & Close.
4.	Select the created Default price list. 

Practice Lab 2 - Skills and characteristics
Task 1 – Create a Security clearance Proficiency Model
Issue: Step 9:  Clarification note needed.  

Work-around:
The user should select Related > Rating Values
 
![image](https://user-images.githubusercontent.com/41710326/104529889-61f5f680-55d0-11eb-8eb9-3864b8fed5de.png)

and then + New Rating Value:

 
![image](https://user-images.githubusercontent.com/41710326/104529905-6a4e3180-55d0-11eb-8f88-0db5c0c8bece.png)

Practice Lab 3 - Resource configuration
Task 1 - Create a Bookable Resource for your user record
Issue: Step 5:  There is no Seattle, Organizational Unit:

 
![image](https://user-images.githubusercontent.com/41710326/104529920-6fab7c00-55d0-11eb-86bc-cca44db0e41a.png)

Work-around:
1.	Click + New Organization Unit
2.	In the confirmation prompt, click Save and continue. 
3.	In the Name field, enter Seattle.
4.	Click the Scheduling tab and enter 47.60801 as the Latitude and -122.33517 as the Longitude.
5.	Click Save & Close. 
6.	In the Organizational Unit field, enter Seattle. 

Practice Lab 3 - Resource configuration
Task 1 - Create a Bookable Resource for your user record
Issue: Step 11:  Directions are unclear here, as there no form change view and our option is + New Bookable Resource not + New

 
![image](https://user-images.githubusercontent.com/41710326/104529936-789c4d80-55d0-11eb-9757-b06de65d8f49.png)

Work-Around:  Click + New Bookable Resource and proceed to step 12. 
Practice Lab 3 - Resource configuration
Task 1 - Create a Bookable Resource for your user record
Issue: Step 14 there is no rating value of Proficient, and the instructions do not call for one to be created prior:

 
![image](https://user-images.githubusercontent.com/41710326/104529961-8e117780-55d0-11eb-96c2-f072a40c073c.png)

Work-around: 
Either an entirely new Rating Model needs to be created or we can leverage the level 5 security created from our proficient.  Assuming Proficient is the best at 5.  

Issue: Same section step 16. There is no familiar.  
Work-around:  Set the rating value to level 3 security, as this would be a happy middle equivalent to Familiar.  
Same Module there is no Name:
 
![image](https://user-images.githubusercontent.com/41710326/104529969-95388580-55d0-11eb-91cf-1d60604a293a.png)

 
![image](https://user-images.githubusercontent.com/41710326/104529984-9ec1ed80-55d0-11eb-8841-c9b278928d87.png)

Work-Around:  Click + New Bookable Resource and proceed to step 12. 
Practice Lab 3 - Resource configuration

Issue: Step 29 advises to select WA as a territory. This territory does not exist. The instructions call for us to create a West, East, South, and North territory:  
 
![image](https://user-images.githubusercontent.com/41710326/104530004-a6819200-55d0-11eb-8e1a-6c6e9442bc12.png)

Work-around: Select on of the pre-created territories.  In notes, suggest name prefix +  North.  

Module 4 - Configure Incidents
Task 1 –Service Task Types to be used with Incidents
Issue: Prior we were in the Resource Scheduling Application. Service Task Types is under the Field Service Application. 
Work-Around: Add a step to navigate to Field Service Application. 

Module 4 - Configure Incidents
Task 3 –Create a Service Printer Incident Type

Issue: Step 24 there is no familiar rating value as the instructions never call for it to be created:

 
![image](https://user-images.githubusercontent.com/41710326/104530037-b305ea80-55d0-11eb-928c-e03563887a16.png)

 
![image](https://user-images.githubusercontent.com/41710326/104530044-b8fbcb80-55d0-11eb-9d13-0a23194e62e2.png)

Work-Around: Select Level 3 Security rating. 

Module 5 - Inventory and Work Order Management
Task 1 - Create a new work order using and incident type
Issue: Step 4   There is no Inspection work order type. 

![image](https://user-images.githubusercontent.com/41710326/104530061-c1ec9d00-55d0-11eb-8f75-0f8c3c75d4ba.png)

 
Work-Around:  
Before Step 1, 
1.	Go to Settings and Work Order Types under Work Orders.  
2.	In the name Field enter Inspection. 
3.	Set the Incident Required and Taxable to No. 
4.	Click Save and Close. 
5.	Under Work Orders go to Incident Types. 
6.	Click + New
7.	In the name field type Install IOT
8.	Click the Details tab and under Default Work Order Type, select Inspection. 
9.	Select Yes for Copy Incident Items to Agreement. 
10.	Click Save and Close.  
11.	Under Work Orders, click Priorities. 
12.	 Click + New.
13.	In the name field type Moderate. 
14.	Click Save & Close. 

Issue: Step 4, there needs to be a step to set the Price List:
 
![image](https://user-images.githubusercontent.com/41710326/104530066-c6b15100-55d0-11eb-8b00-aba2f4fda61e.png)

Issue: Step 5 Service Territory WA was not created in the lab earlier, as we created East/North/South/West.  
Work-Around: Leverage one of the areas you created. Went with name North.  

Module 5 - Inventory and Work Order Management
Task 2 - Schedule the work order using the schedule board
Issue: Step 5 References the AdventureWorks sample.  We created work service tasks but nothing for Adventure works. 

Work-around:  Drag and drop  the moderate work-order you created in the prior task.  

Module 6 - Field Service Agreements
Issue: Task 1 & Task 2 –  This is a duplicate task that was done in Lab 1.  If you try to follow these sections, it throws errors.
Work-Around: These should be removed or an advisory in place to do these if Lab 1 was skipped. 

Module 6 - Field Service Agreements
Exercise 2 - Create an Agreement
Task 1 Create an Agreement to be used for Preventative Maintenance
Issue: Step 2 a note should be added to adjust to service from settings
 
![image](https://user-images.githubusercontent.com/41710326/104530122-ec3e5a80-55d0-11eb-911a-b7904c04dd19.png)

Issue Task 2 - Setup an Automated Booking for the Agreement Step 2:
There is no step to create this work order type prior. 
Work-around:   
1.	Leverage the Inspection work order type you created earlier.  
a.	If you were to author this type to be created, it would need to be much earlier in the lab; as you have saved this to keep open.  
b.	Also, need to add a note to set the preferred resource to the user that you are logged into and the preferred start time to 9:00 am.   

![image](https://user-images.githubusercontent.com/41710326/104530149-f6605900-55d0-11eb-820d-51521acc230f.png)

Issue: Step 10 Again, no Preventative Maintenance type created prior. 
Work-Around:  Leverage the Inspect work-type you created earlier.  

Module 10 - Managing Scheduling Options
Task 2 – Create a Consultation Characteristic
Step 2, there is no Information option for the form:

![image](https://user-images.githubusercontent.com/41710326/104530163-fe1ffd80-55d0-11eb-8570-121547c3ba5d.png)

 
Work-Around:
Create with no Rating Value:
 
![image](https://user-images.githubusercontent.com/41710326/104530173-0415de80-55d1-11eb-9056-5c195d928387.png)

Exercise 2 - Create a new work order using an incident type
Issue: Task 1 – Create a New Work Order from an Incident Type  
Step 5:  There is no WA territory.
Work-Around: Used BRE North (one created earlier as instructed).  Need to add note to select Default as price list as well under Summary:

![image](https://user-images.githubusercontent.com/41710326/104530190-0aa45600-55d1-11eb-997d-753fc56bd94f.png)

 
Exercise 3 - Schedule the work order using the schedule board
Task 1 – Schedule the Work Order you just created
Issue: Step 7 There is never a step to create a work order for Coho Windery.  There is an additional work order available though, suggestion is to just drag and drop this additional one. 
Issue: Step 9 There is no Book Icon that appears and reference to a user Van, which has never been created prior.  
Work-around:  ?? No work-around for these steps. Recommend just removing step 9 and 10 entirely.

**Comment by julians1966** [comment]
Thanks for these suggestions
The MB-230 labs have been completely refreshed and a number of the omissions which you have picked up have been resolved
The labs all now build on each other and do not depend on any existing records or settings
