### ISSUE TITLE
Practise Lab 1 Configure field service - missing "taxable" field on form

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-240-Dynamics365forFieldService#57]
# Lab: 1
#### Step: 10

Description of issue
* There is no "taxable" field on the form.

![image](https://user-images.githubusercontent.com/89986870/229816841-7a1b0470-a7ff-4b7d-9f75-304653899d18.png)

**Comment by ephiax20** [comment]
Hi @chaast apologies for the delay in getting back to you on this.   I am unable to replicate this, using the 'Shared Class' Dynamics 365 environment this course is designed for - the Taxable field is showing on the form. I will contact Skillable to confirm this, as your screenshot does look slightly different to mine but the environment looks similar. 

If this field doesn't show in your environment, there shouldn't be any impact to the rest of the course.

![image](https://github.com/MicrosoftLearning/MB-240-Dynamics365forFieldService/assets/116392278/435f15a0-6569-43ff-8539-a6fd9bb5f1fa)

**Comment by ephiax20** [comment]
Hi @chaast I found this setting, which is set to **Yes** in my environment.   If you still have access, can you check yours??

**Settings** > **Field Service Settings** > **Calculate Tax**

https://learn.microsoft.com/en-us/dynamics365/field-service/set-up-tax-codes

"By default, for all new installations of Field Service v8.8.39.37 or higher, this field will be set to **No**."

![image](https://github.com/MicrosoftLearning/MB-240-Dynamics365forFieldService/assets/116392278/8a77423d-ccc2-48dc-8396-71e4bf0ba392)

**Comment by ephiax20** [comment]
Workaround as above. ^^

We've raised this with the tenant provider.
